name: CI Build & Security Scan
on: [push, pull_request]
permissions:
  actions: read
  contents: read
  security-events: write


jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          GIT_SHA=${{ github.sha }}

          docker build \
          --build-arg GIT_SHA=${GIT_SHA} \
          --build-arg BUILD_DATE=${BUILD_GATE} \
          -t ttapp:${GIT_SHA} .


      - name: Scan Docker image with Trivy and export SARIF
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ttapp:${{ github.sha }}'
          format: sarif
          output: trivy-report.sarif
          exit-code: 0
          severity: HIGH,CRITICAL

      - name: Upload SARIF to Github Security
        uses: github/codeql-action/upload-sarif@v3
        with: 
          sarif_file: trivy-report.sarif

