name: CI Build & Security Scan
on: [push, pull_request]
permissions:
  actions: read
  security-events: write


jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ttapp:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: 'ttapp:latest'
          format: 'sarif'
          exit-code: 0
          severity: HIGH,CRITICAL
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: 'trivy-results.sarif'
