name: CI Build & Security Scan
on: [push, pull_request]
permissions:
  actions: read
  contents: read
  security-events: write


jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ttapp:latest .

      - name: Scan Docker image with Trivy and export SARIF
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ttapp:latest'
          format: sarif
          output: trivy-report.sarif
          exit-code: 0
          severity: HIGH,CRITICAL

      - name: Upload SARIF to Github Security
        uses: github/codeql-action/upload-sarif@v3
        with: 
          sarif_file: trivy-report.sarif

