name: CI Build & Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --tag aryandamle/devops_cicd:${{ github.sha }} \
            .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          image-ref: 'ttapp:latest'
          format: 'sarif'
          exit-code: 0
          severity: HIGH,CRITICAL
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: 'trivy-results.sarif'
